app_mailing/urls.py
from app_mailing.apps import AppMailingConfig
from django.urls import path

from app_mailing.views import (MailingCreateView, MailingDetailView, MailingListView, MailingUpdateView,
                               MailingDeleteView,
                               MailMessageCreateView, MailMessageDetailView, MailMessageListView, MailMessageUpdateView,
                               MailMessageDeleteView, MailingStopView)

app_name = AppMailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/stop', MailingStopView.as_view(), name='mailing_stop'),

    path('mail_messages/', MailMessageListView.as_view(), name='mail_message_list'),
    path('mail_messages/create/', MailMessageCreateView.as_view(), name='mail_message_create'),
    path('mail_messages/<int:pk>/', MailMessageDetailView.as_view(), name='mail_message_detail'),
    path('mail_messages/<int:pk>/update', MailMessageUpdateView.as_view(), name='mail_message_update'),
    path('mail_messages/<int:pk>/delete', MailMessageDeleteView.as_view(), name='mail_message_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page

from landing.views import e_handler404, e_handler403, index_page_view

urlpatterns = [
    path('', cache_page(settings.INDEX_PAGE_CACHE_TIME)(index_page_view), name='index'),
    path("captcha/", include('captcha.urls')),
    path("admin/", admin.site.urls),
    path("accounts/", include('app_accounts.urls', namespace='app_accounts')),
    path("mailings/", include('app_mailing.urls', namespace='app_mailings')),
    path('articles/', include('app_blog.urls', namespace='app_blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = e_handler404
handler403 = e_handler403

app_mailing/models.py
from django.db import models
from django.urls import reverse_lazy

from app_accounts.models import User


class MailMessage(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='mailing_messages',
        verbose_name='Автор сообщения'
    )

    subject = models.CharField(
        max_length=150,
        verbose_name='Тема письма'
    )

    text = models.TextField(
        max_length=1024,
        verbose_name='Текст письма'
    )

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse_lazy('app_mailings:mail_message_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Mailing(models.Model):
    class PeriodicityChoice(models.IntegerChoices):
        DAILY = 0, 'Ежедневно'
        WEEKLY = 1, 'Еженедельно'
        MONTHLY = 2, 'Ежемесячно'

    class MailingStatusChoice(models.IntegerChoices):
        CREATED = 0, 'Создана'
        STARTED = 1, 'Запущена'
        FINISHED = 2, 'Завершена'
        STOPPED = 3, 'Остановлена'

    mailing_owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='mailings',
        verbose_name='Владелец рассылки'
    )

    date_start = models.DateField(
        auto_now=False,
        verbose_name='Дата начала рассылки'
    )

    date_finish = models.DateField(
        auto_now=False,
        verbose_name='Дата окончания рассылки'
    )

    periodicity = models.IntegerField(
        choices=PeriodicityChoice.choices,
        default=PeriodicityChoice.DAILY,
        verbose_name='Периодичность рассылки'
    )

    mailing_status = models.IntegerField(
        choices=MailingStatusChoice.choices,
        default=MailingStatusChoice.CREATED,
        verbose_name='Статус рассылки'
    )

    attempts_count = models.PositiveIntegerField(
        default=1,
        verbose_name='Число повторных попыток',
        help_text='Количество попыток повторной отправки в случае неудачи'
    )

    message = models.ForeignKey(
        MailMessage,
        on_delete=models.CASCADE,
        related_name='mailings',
        verbose_name='Рассылаемое сообщение'
    )

    subscribers = models.ManyToManyField(
        User,
        related_name='subscriptions',
        verbose_name='Получатели'
    )

    def __str__(self):
        return (
            f'{self.message.subject} от '
            f'{self.date_start.strftime("%d %B %Y")} | '
            f'{Mailing.PeriodicityChoice(self.periodicity).label} | '
            f'{Mailing.MailingStatusChoice(self.mailing_status).label}'
        )

    def get_absolute_url(self):
        return reverse_lazy('app_mailings:mailing_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            ('can_stop_mailing', 'Может остановить рассылку')
        ]


class MailingResend(models.Model):
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        verbose_name='Рассылка',
    )

    recipient = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Получатель'
    )

    attempts_left = models.IntegerField(
        default=1,
        verbose_name='Оставшееся число попыток'
    )

    def __str__(self):
        return f'{self.mailing} ({self.recipient.email})'

    class Meta:
        verbose_name = 'Повторная отправка'
        verbose_name_plural = 'Список писем для повторной отправки'
        unique_together = ('mailing', 'recipient')

app_mailing/forms.py
from datetime import datetime

from django import forms

from app_mailing.models import Mailing, MailMessage


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ['mailing_owner']

    def clean_date_start(self):
        date_start = self.cleaned_data.get('date_start')
        if date_start < datetime.now().date():
            raise forms.ValidationError('К сожалению, мы не умеем отправлять письма в прошлое...')
        return date_start

    def clean_date_finish(self):
        date_start = self.cleaned_data.get('date_start')
        if not date_start:
            date_start = datetime.now().date()
        date_finish = self.cleaned_data.get('date_finish')
        if date_finish < date_start:
            raise forms.ValidationError('Время идет в другую сторону... укажите дату окончания позже даты начала')

        return date_finish

    def __init__(self, *args, **kwargs):
        curr_user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['date_start'].initial = datetime.now()
        self.fields['date_finish'].initial = datetime.now()
        if curr_user:
            self.fields['message'].queryset = MailMessage.objects.filter(author=curr_user)
        else:
            self.fields['message'].queryset = MailMessage.objects.none()


class MailingStopForm(forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ['date_start', 'date_finish', 'periodicity', 'message']

    def clean(self):
        self.errors.clear()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_start'].widget.attrs['readonly'] = True
        self.fields['date_finish'].widget.attrs['readonly'] = True
        self.fields['periodicity'].widget.attrs['disabled'] = True
        self.fields['message'].widget.attrs['disabled'] = True
        self.fields['periodicity'].widget.is_required = False
        self.fields['message'].widget.is_required = False


class MailMessageForm(forms.ModelForm):
    class Meta:
        model = MailMessage
        fields = '__all__'
        exclude = ['author']

app_mailing/views/mail_message_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView

from app_mailing.forms import MailMessageForm
from app_mailing.models import MailMessage


class MailMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailMessage
    form_class = MailMessageForm

    def form_valid(self, form):
        new_obj: MailMessage = form.save(commit=False)
        new_obj.author = self.request.user
        new_obj.save()
        return redirect(new_obj.get_absolute_url())


class MailMessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = MailMessage

    def test_func(self):
        curr_user = self.request.user
        return (self.get_object().author == curr_user or
                self.request.user.has_perm('app_mailing.view_mailmessage'))


class MailMessageListView(LoginRequiredMixin, ListView):
    model = MailMessage

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.has_perm('app_mailing.view_mailmessage'):
            queryset.filter(author=self.request.user)
        return queryset


class MailMessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MailMessage
    form_class = MailMessageForm

    def test_func(self):
        curr_user = self.request.user
        return (self.get_object().author == curr_user or
                self.request.user.has_perm('app_mailing.change_mailmessage'))


class MailMessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = MailMessage

    success_url = reverse_lazy('app_mailings:mail_message_list')

    def test_func(self):
        curr_user = self.request.user
        return self.get_object().author == curr_user

    def get_template_names(self):
        return 'shared/model_confirm_delete.html'

app_mailing/views/mailing_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView

from app_mailing.forms import MailingForm, MailingStopForm
from app_mailing.models import Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        new_obj: Mailing = form.save(commit=False)
        new_obj.mailing_owner = self.request.user
        new_obj.save()
        for subscriber in form.cleaned_data['subscribers']:
            new_obj.subscribers.add(subscriber)
        new_obj.save()
        return redirect(new_obj.get_absolute_url())


class MailingDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Mailing

    def test_func(self):
        curr_user = self.request.user
        return (self.get_object().mailing_owner == curr_user or
                self.request.user.has_perm('app_mailing.view_mailing'))


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.has_perm('app_mailing.view_mailing'):
            queryset = queryset.filter(mailing_owner=self.request.user)
        return queryset


class MailingStopView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingStopForm
    template_name = 'app_mailing/mailing_stop.html'

    def test_func(self):
        curr_user = self.request.user
        return curr_user.has_perm('app_mailing.can_stop_mailing')

    def form_valid(self, form):
        new_obj: Mailing = form.save(commit=False)
        new_obj.mailing_status = Mailing.MailingStatusChoice.STOPPED
        new_obj.save()
        return redirect(reverse_lazy('app_mailings:mailing_list'))


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm

    def test_func(self):
        curr_user = self.request.user
        return self.get_object().mailing_owner == curr_user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('app_mailings:mailing_list')

    def test_func(self):
        curr_user = self.request.user
        return self.get_object().mailing_owner == curr_user

    def get_template_names(self):
        return 'shared/model_confirm_delete.html'

templates/app_mailing/mailing_detail.html
{% extends 'shared/_base.html' %}

{% block title %}
  {{ block.super }} - {{ object }}
{% endblock %}

{% block content %}
  <div class="btn-toolbar my-4" role="toolbar">
    <div class="btn-group btn-group-sm me-2" role="group">
      <a class="btn btn-outline-primary" href="{% url 'app_mailings:mailing_list' %}">
        <i class="bi bi-list"></i>
        Список</a>
      <a class="btn btn-outline-success" href="{% url 'app_mailings:mailing_create' %}">
        <i class="bi bi-send-plus"></i>
        Создать новую</a>
    </div>
    <div class="btn-group btn-group-sm me-2" role="group">
      {% if user.pk == object.mailing_owner.pk or perms.app_mailing.change_mailing %}
        <a class="btn btn-outline-success" href="{% url 'app_mailings:mailing_update' object.pk %}">
          <i class="bi bi-pencil"></i>
          Править</a>
      {% endif %}
      {% if perms.app_mailing.delete_mailing or user.pk == object.mailing_owner.pk %}
        <a class="btn btn-outline-danger" href="{% url 'app_mailings:mailing_delete' object.pk %}">
          <i class="bi bi-trash"></i>
          Удалить</a>
      {% endif %}
    </div>
  </div>

  <p>{{ object.mailing_owner }}</p>
  <p>{{ object.message.subject }}</p>
  <p>{{ object.message.text }}</p>
  <ul>
    {% for subscriber in object.subscribers.all %}
      <li>{{ subscriber.email }}</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/app_mailing/mailing_form.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {{ block.super }} - {% if object %}Редактирование{% else %}Создание{% endif %} рассылки
{% endblock %}

{% block content %}
  <form class="mt-5" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout="floating" %}

    <button class="btn btn-success" type="submit">Сохранить</button>
    <a class="btn btn-secondary"
       href="{% if object %}{{ object.get_absolute_url }}{% else %}{% url 'app_mailings:mailing_list' %}{% endif %}">Отмена</a>

  </form>
{% endblock %}

templates/app_mailing/mailing_list.html
{% extends 'shared/_base.html' %}
{% block title %}
  {{ block.super }} - Рассылки
{% endblock %}
{% block content %}
  <div class="btn-toolbar my-4" role="toolbar">
    <div class="btn-group btn-group-sm">
      <a class="btn btn-outline-success" href="{% url 'app_mailings:mailing_create' %}">
        <i class="bi bi-send-plus"></i>
        Создать</a>
    </div>
  </div>
  <table class="table table-striped table-hover mt-5">
    <thead>
    <tr>
      <th>Рассылка</th>
      <th>Владелец</th>
      <th>Периодичность</th>
      <th>Статус</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}

      <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        <td>{{ object.mailing_owner }}</td>
        <td>{{ object.get_periodicity_display }}</td>
        <td>
          {% if object.mailing_status == 3 %}
          	<i class="bi bi-exclamation-triangle text-warning-emphasis"></i>
          {% endif %}
          {{ object.get_mailing_status_display }}
        </td>
        <td>

        <div class="btn-group btn-group-sm" role="group">
              {% if user.pk == object.mailing_owner.pk %}
                <a href="{% url 'app_mailings:mailing_update' object.pk %}" class="btn btn-outline-primary"><i
                    class="bi bi-pencil"></i></a>
              {% endif %}
              {% if perms.app_mailing.can_stop_mailing and object.mailing_status == 1 and not user.pk == object.pk %}
                <a href="{% url 'app_mailings:mailing_stop' object.pk %}" class="btn btn-outline-warning">
                    <i class="bi bi-stop"></i>
                </a>
              {% endif %}
            </div>
        </td>
      </tr>

    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/app_mailing/mailing_stop.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {{ block.super }} - {% if object %}Редактирование{% else %}Создание{% endif %} рассылки
{% endblock %}

{% block content %}
  <form class="mt-5" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout="floating" %}

    <button class="btn btn-warning" type="submit">Остановить</button>
    <a class="btn btn-secondary"
       href="{% url 'app_mailings:mailing_list' %}">Отмена</a>

  </form>
{% endblock %}

templates/app_mailing/mailmessage_detail.html
{% extends 'shared/_base.html' %}

{% block title %}
  {{ block.super }} - {{ object }}
{% endblock %}

{% block content %}
  <div class="btn-toolbar my-4" role="toolbar">
    <div class="btn-group btn-group-sm me-2" role="group">
      <a class="btn btn-outline-primary" href="{% url 'app_mailings:mail_message_list' %}">
        <i class="bi bi-list"></i>
        Список</a>
      <a class="btn btn-outline-success" href="{% url 'app_mailings:mail_message_create' %}">
        <i class="bi bi-envelope-plus"></i>
        Создать новое</a>
    </div>
    <div class="btn-group btn-group-sm me-2" role="group">
      {% if perms.app_mailing.change_mailmessage or user.pk == object.author.pk %}
      <a class="btn btn-outline-success" href="{% url 'app_mailings:mail_message_update' object.pk %}">
        <i class="bi bi-pencil"></i>
        Править</a>
      {% endif %}
      {% if perms.app_mailing.delete_mailmessage or user.pk == object.mailing_owner.pk %}
      <a class="btn btn-outline-danger" href="{% url 'app_mailings:mail_message_delete' object.pk %}">
        <i class="bi bi-trash"></i>
        Удалить</a>
      {% endif %}
    </div>
  </div>

  <p>{{ object.author }}</p>
  <p>{{ object.subject }}</p>
  <p>{{ object.text }}</p>
  <ul>
    {% for subscriber in object.subscribers.all %}
      <li>{{ subscriber.email }}</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/app_mailing/mailmessage_form.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {{ block.super }} - {% if object %}Редактирование{% else %}Создание{% endif %} письма для рассылки
{% endblock %}

{% block content %}
  <form class="mt-5" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout="floating" %}
    <button class="btn btn-success" type="submit">Сохранить</button>

    <a class="btn btn-secondary" href="
        {% if object %}{{ object.get_absolute_url }}{% else %}{% url 'app_mailings:mail_message_list' %}{% endif %}">Отмена</a>

  </form>
{% endblock %}

templates/app_mailing/mailmessage_list.html
{% extends 'shared/_base.html' %}
{% block title %}
  {{ block.super }} - Письма для рассылок
{% endblock %}
{% block content %}
  <div class="btn-toolbar my-4" role="toolbar">
    <div class="btn-group btn-group-sm">
      <a class="btn btn-outline-success" href="{% url 'app_mailings:mail_message_create' %}">
        <i class="bi bi-envelope-plus"></i>
        Создать</a>
    </div>
  </div>
  <table class="table table-striped table-hover mt-5">
    <thead>
    <tr>
      <th>Тема</th>
      <th>Владелец</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
      <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        <td>{{ object.author }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}