app_accounts/urls.py
from app_accounts.apps import AppAccountsConfig
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from app_accounts.views import UserDetailView, UserResetPassword, UserEmailVerify, UserCreateView, UserEditView, \
    VerifyMailAgain, UserPasswordChangeView, UserListView, UserBlockUnblockView

app_name = AppAccountsConfig.name

urlpatterns = [
    path('', UserDetailView.as_view(), name='user_detail'),
    path('list/', UserListView.as_view(), name='users_list'),
    path('<int:pk>/block/', UserBlockUnblockView.as_view(), name='user_block'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('registration/email_verify/<uidb64>/<token>/', UserEmailVerify.as_view(), name='email_verify'),
    path('registration/email_verify/resend', VerifyMailAgain.as_view(), name='email_verify_again'),
    path('reset_password/', UserResetPassword.as_view(), name='reset_password'),
    path('edit/', UserEditView.as_view(), name='user_edit'),
    path('password/', UserPasswordChangeView.as_view(), name='change_password'),

    path('login/', LoginView.as_view(
        template_name='app_accounts/login.html',
    ),
         name='login',
         ),

    path('registration/email_verify/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify.html',
    ),
         name='email_verify_alert'
         ),

    path('registration/email_verify_failed/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify_failed.html',
    ),
         name='email_verify_failed'
         ),

    path('reset_password/success', TemplateView.as_view(
        template_name='app_accounts/reset_password_success.html',
    ),
         name='reset_password_alert'
         ),
]

app_blog/urls.py
from django.urls import path

from app_blog.apps import AppBlogConfig
from app_blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = AppBlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page

from landing.views import e_handler404, e_handler403, index_page_view

urlpatterns = [
    path('', cache_page(settings.INDEX_PAGE_CACHE_TIME)(index_page_view), name='index'),
    path("captcha/", include('captcha.urls')),
    path("admin/", admin.site.urls),
    path("accounts/", include('app_accounts.urls', namespace='app_accounts')),
    path("mailings/", include('app_mailing.urls', namespace='app_mailings')),
    path('articles/', include('app_blog.urls', namespace='app_blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = e_handler404
handler403 = e_handler403

app_blog/models.py
import pytils.translit
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from app_accounts.models import User
from utils.hash_storage import HashStorage, article_preview_images
from utils.const import MF_NULL


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=170, unique=True, null=True)
    content_text = models.TextField(max_length=2048, verbose_name='текст статьи')
    preview_image = models.ImageField(upload_to=article_preview_images, storage=HashStorage(),
                                      verbose_name='превью', **MF_NULL)
    create_date = models.DateTimeField(default=timezone.now, verbose_name='дата создания')
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='articles', **MF_NULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('app_blog:article_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        max_len = self._meta.get_field('slug').max_length
        slug = pytils.translit.slugify(self.title)[:max_len]
        slug = f'{slug}_{self.pk}'
        self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

app_blog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from app_blog.apps import AppBlogConfig
from app_blog.models import Article


class ArticleListView(ListView):
    model = Article
    paginate_by = AppBlogConfig.articles_per_page

    def get_queryset(self):
        if not settings.CACHE_ENABLED:

            qs = super().get_queryset()
            qs = qs.filter(is_published=True).order_by('-create_date')

            return qs

        return cache.get_or_set(
            key=f'article_list_{self.request.GET.get("page",1)}',
            default=super().get_queryset().filter(is_published=True).order_by('-create_date'),
            timeout=settings.ARTICLES_PAGE_CACHE_TIME
        )


class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['popular'] = Article.objects.filter(is_published=True).filter(~Q(id=self.object.id)).order_by(
            '-view_count')[:3]
        return ctx

    def get_object(self, queryset=None):
        if not settings.CACHE_ENABLED:
            self.object = super().get_object(queryset)
            self.object.view_count += 1
            self.object.save()
        else:
            key = f'article_{self.request.path}'
            key_views = f'{key}_views'
            self.object = cache.get_or_set(
                key=key,
                default=super().get_object(queryset),
                timeout=settings.ARTICLES_PAGE_CACHE_TIME
            )

            cached_views = cache.get_or_set(
                key=key_views,
                default=1,
                timeout=50
            )
            cached_views += 1
            cache.set(key_views, cached_views)

            if cached_views >= settings.ARTICLE_CACHED_VIEW_COUNT:
                db_obj = super().get_object(queryset)
                db_obj.view_count += cached_views
                db_obj.save()
                cache.delete(key_views)
                cache.delete(key)
                self.object = db_obj

        return self.object


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ('title', 'content_text', 'preview_image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_obj = form.save(commit=False)
            new_obj.author = self.request.user
            new_obj.save()
            return redirect(reverse('app_blog:article_detail', kwargs={'slug': new_obj.slug}))


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'content_text', 'preview_image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_obj = form.save()
            return redirect(reverse('app_blog:article_detail', kwargs={'slug': new_obj.slug}))


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('app_blog:articles')

    def test_func(self):
        curr_user = self.request.user
        return self.get_object().mailing_owner == curr_user

    def get_template_names(self):
        return 'shared/model_confirm_delete.html'

templates/app_blog/article_detail.html
{% extends 'shared/_base.html' %}
{% block title %}
  {{ block.super }} - {{ object.title }}
{% endblock %}
{% block content %}
  {% if object.author and user.pk == object.author.pk or user.is_staff %}
    <div class="btn-toolbar my-4" role="toolbar">
      <div class="btn-group btn-group-sm me-2" role="group">
        <a class="btn btn-outline-primary" href="{% url 'app_accounts:user_detail' %}">
          <i class="bi bi-list"></i>
          Мои статьи</a>
        <a class="btn btn-outline-success" href="{% url 'app_blog:article_create' %}">
          <i class="bi bi-file-earmark-plus"></i>
          Создать новую</a>
      </div>
      <div class="btn-group btn-group-sm me-2" role="group">

        <a class="btn btn-outline-success" href="{% url 'app_blog:article_update' object.slug %}">
          <i class="bi bi-pencil"></i>
          Править</a>
        <a class="btn btn-outline-danger" href="{% url 'app_blog:article_delete' object.slug %}">
          <i class="bi bi-trash"></i>
          Удалить</a>
      </div>
    </div>
  {% endif %}
  <article class="pt-3">
    <h1 class="">{{ object.title }}</h1>

    {% if object.preview_image %}
      <img src="{{ object.preview_image.url }}" class="object-fit-cover w-100 mb-4 bottom-transparent"
           style="height: 400px;" alt="">
    {% endif %}
    <p>{{ object.content_text }}</p>
    <div class="text-end mt-5">
      <time class="text-secondary">{{ object.create_date }}</time>
    </div>

    <div class="text-end">
      <small class="text-muted">Статью просмотрели {{ object.view_count }} раз</small>
      <p class="text-muted mt-2">Автор
        {% if object.author.full_name %}
        <strong>{{ object.author.full_name }}</strong>
      {% else %}
        к сожалению не представился
      {% endif %} </p>
    </div>
  </article>
  <div>
    <h5 class="mt-5 pt-2 border-top">Популярное</h5>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
      {% for article in popular %}
        <div class="col">
          <div class="card mb-3 h-100" style="max-width: 540px;">
            <div class="card-body">
              <h6 class="card-title">{{ article.title }}</h6>
              <p class="card-text">{{ article.content_text|truncatechars:100 }}</p>

              <p class="card-text text-end">
                <small class="text-body-secondary ">{{ article.create_date }}</small>
              </p>
              <a href="{% url 'app_blog:article_detail' article.slug %}" class="stretched-link"></a>
            </div>

            <div class="card-footer">
              <small class="text-body-secondary">{{ article.view_count }} просмотров</small>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
  </div>
{% endblock %}

templates/app_blog/article_form.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {{ block.super }} - {% if object %}Редактирование {{ object.title }}{% else %}Новая публикация{% endif %}
{% endblock %}
{% block content %}
    <form class="mt-5" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}
        <div class="mb-3 btn-group" role="group">
            {% if object %}
                <a href="{% url 'app_blog:article_detail' object.slug %}" class="btn btn-secondary nav-back">Отмена</a>
            {% endif %}
            <button class="btn btn-success" type="submit">Сохранить</button>
        </div>

    </form>
{% endblock %}

templates/app_blog/article_list.html
{% extends 'shared/_base.html' %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
     <div class="btn-toolbar my-4" role="toolbar">
      <div class="btn-group btn-group-sm me-2" role="group">
        <a class="btn btn-outline-primary" href="{% url 'app_accounts:user_detail' %}">
          <i class="bi bi-list"></i>
          Мои статьи</a>
        <a class="btn btn-outline-success" href="{% url 'app_blog:article_create' %}">
          <i class="bi bi-file-earmark-plus"></i>
          Создать новую</a>
      </div>
    </div>
  {% endif %}

  <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
    {% for object in object_list %}
      <div class="col">
        <div class="card mb-3 h-100" style="max-width: 540px;">
          {% if object.preview_image %}
            <img src="{{ object.preview_image.url }}" class="card-img-top object-fit-cover w-100"
                 alt="object.title">
          {% endif %}

          <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.content_text|truncatechars:250 }}</p>

            <p class="card-text text-end">
              <small class="text-body-secondary ">{{ object.create_date }}</small>
            </p>
            <a href="{% url 'app_blog:article_detail' object.slug %}" class="stretched-link"></a>
          </div>

          <div class="card-footer">
            <small class="text-body-secondary">{{ object.view_count }} просмотров</small>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  {% if is_paginated %}
    <nav aria-label="Страницы с товарами" class="mt-4">
      <ul class="pagination justify-content-center">
        <li class="page-item {% if page_obj.has_previous == False %}disabled{% endif %}">
          <a
              class="page-link"
              href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}
                            {% else %}#{% endif %}"
              aria-label="Предыдущая">
            <span aria-hidden="true">&laquo;</span></a>
        </li>

        {% for page_id in page_obj.paginator.page_range %}
          {% if page_obj.number == page_id %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">{{ page_id }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_id }}">{{ page_id }}</a>
            </li>
          {% endif %}
        {% endfor %}
        <li class="page-item {% if page_obj.has_next == False %}disabled{% endif %}">
          <a class="page-link"
             href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}"
             aria-label="Следующая"><span aria-hidden="true">&raquo;</span></a>
        </li>
      </ul>
    </nav>
  {% endif %}
{% endblock %}