app_accounts/urls.py
from app_accounts.apps import AppAccountsConfig
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from app_accounts.views import UserDetailView, UserResetPassword, UserEmailVerify, UserCreateView, UserEditView, \
    VerifyMailAgain, UserPasswordChangeView, UserListView, UserBlockUnblockView

app_name = AppAccountsConfig.name

urlpatterns = [
    path('', UserDetailView.as_view(), name='user_detail'),
    path('list/', UserListView.as_view(), name='users_list'),
    path('<int:pk>/block/', UserBlockUnblockView.as_view(), name='user_block'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('registration/email_verify/<uidb64>/<token>/', UserEmailVerify.as_view(), name='email_verify'),
    path('registration/email_verify/resend', VerifyMailAgain.as_view(), name='email_verify_again'),
    path('reset_password/', UserResetPassword.as_view(), name='reset_password'),
    path('edit/', UserEditView.as_view(), name='user_edit'),
    path('password/', UserPasswordChangeView.as_view(), name='change_password'),

    path('login/', LoginView.as_view(
        template_name='app_accounts/login.html',
    ),
         name='login',
         ),

    path('registration/email_verify/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify.html',
    ),
         name='email_verify_alert'
         ),

    path('registration/email_verify_failed/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify_failed.html',
    ),
         name='email_verify_failed'
         ),

    path('reset_password/success', TemplateView.as_view(
        template_name='app_accounts/reset_password_success.html',
    ),
         name='reset_password_alert'
         ),
]

app_blog/urls.py
from django.urls import path

from app_blog.apps import AppBlogConfig
from app_blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = AppBlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

app_mailing/urls.py
from app_mailing.apps import AppMailingConfig
from django.urls import path

from app_mailing.views import (MailingCreateView, MailingDetailView, MailingListView, MailingUpdateView,
                               MailingDeleteView,
                               MailMessageCreateView, MailMessageDetailView, MailMessageListView, MailMessageUpdateView,
                               MailMessageDeleteView, MailingStopView)

app_name = AppMailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/stop', MailingStopView.as_view(), name='mailing_stop'),

    path('mail_messages/', MailMessageListView.as_view(), name='mail_message_list'),
    path('mail_messages/create/', MailMessageCreateView.as_view(), name='mail_message_create'),
    path('mail_messages/<int:pk>/', MailMessageDetailView.as_view(), name='mail_message_detail'),
    path('mail_messages/<int:pk>/update', MailMessageUpdateView.as_view(), name='mail_message_update'),
    path('mail_messages/<int:pk>/delete', MailMessageDeleteView.as_view(), name='mail_message_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page

from landing.views import e_handler404, e_handler403, index_page_view

urlpatterns = [
    path('', cache_page(settings.INDEX_PAGE_CACHE_TIME)(index_page_view), name='index'),
    path("captcha/", include('captcha.urls')),
    path("admin/", admin.site.urls),
    path("accounts/", include('app_accounts.urls', namespace='app_accounts')),
    path("mailings/", include('app_mailing.urls', namespace='app_mailings')),
    path('articles/', include('app_blog.urls', namespace='app_blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = e_handler404
handler403 = e_handler403

landing/views.py
from django.conf import settings
from django.db.models import Q
from django.template import RequestContext
from django.shortcuts import render

from app_blog.models import Article
from app_mailing.models import Mailing


def e_handler403(request, exception):
    return render(request, 'shared/errors/403.html', status=403)


def e_handler404(request, exception):
    return render(request, 'shared/errors/404.html', status=404)


def index_page_view(request, *args, **kwargs):
    return render(request, 'landing/index.html', context={
        'popular_articles': Article.objects.order_by('-view_count')[:settings.POPULAR_ARTICLES_COUNT],
        'active_mailing': len(Mailing.objects.filter(mailing_status=Mailing.MailingStatusChoice.STARTED)),
        'total_mailing': len(Mailing.objects.filter(~Q(mailing_status=Mailing.MailingStatusChoice.STOPPED)))
    })

templates/landing/index.html
{% extends 'shared/_base.html' %}

{% block content %}
  <section class="my-5">
    <h2>Сервис почтовых рассылок</h2>
    {% if not user.is_authenticated %}
      <p class="my-2">
        Чтобы воспользоваться всеми преимуществами платформы
        <a class="link-light" href="{% url 'app_accounts:login' %}">войдите</a> или
        <a class="link-light" href="{% url 'app_accounts:registration' %}">зарегистрируйтесь</a>
      </p>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-2 g-4 mt-3">
      <div class="col">
        <div class="card text-center h-100">
          <div class="card-header">
            Активно рассылок
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
            <strong style="font-size: 10rem">{{ active_mailing }}</strong>
            <footer class="blockquote-footer">Каждый день мы доставляем актуальную информацию вашим подписчикам</footer>
            </blockquote>

          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-center h-100">
          <div class="card-header">
            Всего создано рассылок
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
            <strong style="font-size: 10rem">{{ total_mailing }}</strong>
            <footer class="blockquote-footer">Создайте вашу рассылку, и расслабтесь с чашечкой хорошего кофе.<br>
              А мы сделаем за вас вашу рутину</footer>
            </blockquote>

          </div>
        </div>
      </div>
    </div>

    <div class="text-center mt-4">
      <a href="{% url 'app_mailings:mailing_list' %}" class="btn btn-success btn-lg m-3">Начать пользоваться</a>
    </div>

  </section>




  {% if popular_articles %}
    <h5 class="mt-5 pt-2 {% if popular_products %}border-top{% endif %}">Популярные статьи</h5>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
      {% for article in popular_articles %}
        <div class="col">
          <div class="card mb-3 h-100" style="max-width: 540px;">
            <div class="card-body">
              <h6 class="card-title">{{ article.title }}</h6>
              <p class="card-text">{{ article.content_text|truncatechars:100 }}</p>

              <p class="card-text text-end">
                <small class="text-body-secondary ">{{ article.create_date }}</small>
              </p>
              <a href="{% url 'app_blog:article_detail' article.slug %}" class="stretched-link"></a>
            </div>

            <div class="card-footer">
              <small class="text-body-secondary">{{ article.view_count }} просмотров</small>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}

{% endblock %}