app_accounts/urls.py
from app_accounts.apps import AppAccountsConfig
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from app_accounts.views import UserDetailView, UserResetPassword, UserEmailVerify, UserCreateView, UserEditView, \
    VerifyMailAgain, UserPasswordChangeView, UserListView, UserBlockUnblockView

app_name = AppAccountsConfig.name

urlpatterns = [
    path('', UserDetailView.as_view(), name='user_detail'),
    path('list/', UserListView.as_view(), name='users_list'),
    path('<int:pk>/block/', UserBlockUnblockView.as_view(), name='user_block'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('registration/email_verify/<uidb64>/<token>/', UserEmailVerify.as_view(), name='email_verify'),
    path('registration/email_verify/resend', VerifyMailAgain.as_view(), name='email_verify_again'),
    path('reset_password/', UserResetPassword.as_view(), name='reset_password'),
    path('edit/', UserEditView.as_view(), name='user_edit'),
    path('password/', UserPasswordChangeView.as_view(), name='change_password'),

    path('login/', LoginView.as_view(
        template_name='app_accounts/login.html',
    ),
         name='login',
         ),

    path('registration/email_verify/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify.html',
    ),
         name='email_verify_alert'
         ),

    path('registration/email_verify_failed/', TemplateView.as_view(
        template_name='app_accounts/user_email_verify_failed.html',
    ),
         name='email_verify_failed'
         ),

    path('reset_password/success', TemplateView.as_view(
        template_name='app_accounts/reset_password_success.html',
    ),
         name='reset_password_alert'
         ),
]

app_blog/urls.py
from django.urls import path

from app_blog.apps import AppBlogConfig
from app_blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = AppBlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page

from landing.views import e_handler404, e_handler403, index_page_view

urlpatterns = [
    path('', cache_page(settings.INDEX_PAGE_CACHE_TIME)(index_page_view), name='index'),
    path("captcha/", include('captcha.urls')),
    path("admin/", admin.site.urls),
    path("accounts/", include('app_accounts.urls', namespace='app_accounts')),
    path("mailings/", include('app_mailing.urls', namespace='app_mailings')),
    path('articles/', include('app_blog.urls', namespace='app_blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = e_handler404
handler403 = e_handler403

app_accounts/models.py
from django.apps import apps
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    first_name = None
    last_name = None

    email = models.EmailField(
        unique=True
    )

    full_name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='ФИО'
    )

    comment = models.CharField(
        max_length=250,
        verbose_name='Комментарий',
        null=True,
        blank=True,
    )

    is_email_verify = models.BooleanField(
        default=False,
        verbose_name='Почта подтверждена'
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    @property
    def short_str(self):
        return f'{self.full_name}' if self.full_name else self.email

    def __str__(self):
        return f'{self.full_name} ({self.email})' if self.full_name else self.email

    class Meta:
        permissions = [
            ('can_block_users', 'Может блокировать пользователей')
        ]

app_accounts/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from app_accounts.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'full_name', 'password1', 'password2')


class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('full_name', 'comment')


class UserBlockUnblockForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('full_name', 'email', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True


class UserResetPasswordForm(forms.Form):
    user_email = forms.EmailField()
    captcha = CaptchaField()

    def clean_user_email(self):
        # TODO: if captcha invalid raise exception
        email = self.cleaned_data.get('user_email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователя с таким email не найдено!')
        return email

app_accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, UpdateView, CreateView, FormView, ListView
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.utils.http import urlsafe_base64_decode

from app_accounts.forms import UserResetPasswordForm, UserRegisterForm, UserEditForm, UserBlockUnblockForm
from app_accounts.models import User
from app_accounts.services import send_email_to_verify, send_new_user_password


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    login_url = reverse_lazy('app_accounts:login')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['title'] = 'Информация об аккаунте'
        return ctx

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User

    def test_func(self):
        curr_user = self.request.user
        return any([
            curr_user.has_perm('app_accounts.view_user'),
            curr_user.has_perm('app_accounts.can_block_users')
        ])


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'app_accounts/register.html'
    success_url = reverse_lazy('app_accounts:login')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            login(self.request, self.object)
            send_email_to_verify(self.object.id, get_current_site(self.request).id)
            return redirect(reverse_lazy('app_accounts:email_verify_alert'))

        return self.render_to_response(self.get_context_data(form=form))


class UserEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'app_accounts/user_edit.html'
    success_url = reverse_lazy('app_accounts:user_detail')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        if form.is_valid():
            user = form.save()
            login(self.request, user)
            return redirect(reverse_lazy('app_accounts:user_detail'))
        return self.render_to_response(self.get_context_data(form=form))


class UserPasswordChangeView(PasswordChangeView):
    form_class = SetPasswordForm
    template_name = 'app_accounts/user_password_change.html'

    def get_success_url(self):
        return reverse_lazy('app_accounts:user_detail')


class UserEmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.is_email_verify = True
            user.save()
            login(request, user)
            return redirect(reverse_lazy('app_accounts:user_detail'))
        return redirect(reverse_lazy('app_accounts:email_verify_failed'))

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


class VerifyMailAgain(LoginRequiredMixin, View):
    login_url = reverse_lazy('app_accounts:login')

    def get(self, request):
        send_email_to_verify(request.user.id, get_current_site(request).id)
        return redirect(reverse_lazy('app_accounts:email_verify_alert'))


class UserResetPassword(FormView):
    form_class = UserResetPasswordForm
    template_name = 'app_accounts/reset_password.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['title'] = 'Сброс пароля'
        return ctx

    def form_valid(self, form):
        if form.is_valid():
            email = form.data['user_email']
            new_password = User.objects.make_random_password()
            user = User.objects.get(email=email)
            user.set_password(new_password)
            user.save()

            send_new_user_password(user.id, new_password, get_current_site(self.request).id)

            return redirect(reverse_lazy('app_accounts:reset_password_alert'))


class UserBlockUnblockView(UpdateView):
    model = User
    template_name = 'app_accounts/user_edit.html'
    form_class = UserBlockUnblockForm

    def get_success_url(self):
        return reverse_lazy('app_accounts:users_list')

templates/app_accounts/block_unblock_user.html
{% extends 'shared/_base.html' %}

{% block title %}
	Управление блокировкой пользователя
{% endblock %}

{% block content %}
	<div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}
        <div class="hstack gap-3 my-4">
          <a class="btn btn-secondary" href="{% url 'app_accounts:user_detail' %}">Отмена</a>
          <button class="btn btn-success" type="submit">Сохранить</button>
        </div>
      {% endwith %}
    </form>
  </div>
{% endblock %}

templates/app_accounts/login.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
	{{ block.super }} - Войти
{% endblock %}
{% block content %}
  <div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}

        {% bootstrap_form form layout="floating" %}

        <div class="d-flex justify-content-center my-4">
          <button class="btn btn-lg btn-success w-100" type="submit">Войти</button>
        </div>
        <div class="d-flex justify-content-center">
          <a href="{% url 'app_accounts:reset_password' %}" class="link-secondary">Забыли пароль</a>
        </div>
        <div class="d-flex justify-content-center">
          <a href="{% url 'app_accounts:registration' %}">Регистрация</a>
        </div>
      {% endwith %}
    </form>
  </div>
{% endblock %}

templates/app_accounts/register.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
	{{ block.super }} - Регистрация нового пользователя
{% endblock %}
{% block content %}

  <div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}

        <div class="d-flex justify-content-center my-4">
          <button class="btn btn-lg btn-success w-100" type="submit">Зарегистрироваться</button>
        </div>
      {% endwith %}
    </form>
  </div>
{% endblock %}

templates/app_accounts/reset_password.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
	{{ block.super }} - Сброс пароля
{% endblock %}
{% block content %}
  <div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}
        <div class="d-flex justify-content-center mt-4">
          <button type="submit" class="btn btn-success">Сбросить пароль</button>
        </div>
      {% endwith %}
    </form>
  </div>
{% endblock %}

templates/app_accounts/reset_password_success.html
{% extends 'shared/_base.html' %}
{% block title %}
  {{ block.super }} - Подтверждение адреса почты
{% endblock %}
{% block content %}
  <p class="mt-5">Мы выслали на указанную вами почту новый пароль.
    Теперь вы можете <a href="{% url 'app_accounts:login' %}">войти</a> с его помощью</p>
  <div class="alert alert-secondary mt-2">
    <i class="bi bi-info-circle"></i>
    Если сообщение не пришло в течении получаса, проверьте папку "спам" или повторите попытку снова
  </div>

{% endblock %}

templates/app_accounts/user_detail.html
{% extends 'shared/_base.html' %}
{% block title %}
	{{ block.super }} - Профиль
{% endblock %}
{% block content %}

  <div class="accordion pt-5" id="accordionPanelsStayOpenExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                aria-controls="panelsStayOpen-collapseOne">
          Аккаунт
        </button>
      </h2>
      <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
        <div class="accordion-body">
          <div class="table-responsive">
            <table class="table table-striped">
              <tr>
                <th>Имя:</th>
                <td>{% if user.full_name %}
                  {{ user.full_name }}
                {% else %}
                  -
                {% endif %} </td>
              </tr>
              <tr>
                <th>email:</th>
                <td>
                  {{ user.email }}
                  {% if not user.is_email_verify %}
                    <p class="text-warning-emphasis">Адрес почты не подтвержден!</p>
                    <a href="{% url 'app_accounts:email_verify_again' %}">Выслать ссылку подтверждения повторно</a>
                  {% endif %}
                </td>
              </tr>
              <tr>
                <th>Последний вход:</th>
                <td>{{ user.last_login }}</td>
              </tr>
            </table>
          </div>
          <div class="btn-toolbar">
            <div class="btn-group btn-group-sm">
              <a class="btn btn-outline-secondary" href="{% url 'app_accounts:user_edit' %}">Редактировать профиль</a>
              <a class="btn btn-outline-secondary" href="{% url 'app_accounts:change_password' %}">Сменить пароль</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% if user.articles.exists %}
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                  aria-controls="panelsStayOpen-collapseThree">
            Ваши статьи
          </button>
        </h2>
        <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
          <div class="accordion-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover align-middle">
                <thead>
                <tr>
                  <th>Название</th>
                  <th>Просмотров</th>
                  <th>Дата написания</th>
                  <th>Статус публикации</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                {% for article in user.articles.all %}
                  <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.view_count }}</td>
                    <td>{{ article.create_date }}</td>
                    <td>
                      {% if article.is_published %}
                        <span class="text-success-emphasis">Опубликовано</span>
                      {% else %}
                        <span class="text-secondary-emphasis">Не опубликовано</span>
                      {% endif %}
                    </td>
                    <td>
                      <div class="btn-group btn-group-sm">
                        <a class="btn btn-outline-secondary" href="{% url 'app_blog:article_detail' article.slug %}"
                           target="_blank" rel="noopener noreferrer" title="Читать">
                          <i class="bi bi-eye"></i>
                        </a>
                        <a class="btn btn-outline-primary" href="{% url 'app_blog:article_update' article.slug %}"
                           target="_blank"
                           rel="noopener noreferrer" title="Редактировать">
                          <i class="bi bi-pencil"></i>
                        </a>
                        <a class="btn btn-outline-danger" href="{% url 'app_blog:article_delete' article.slug %}"
                           target="_blank"
                           rel="noopener noreferrer" title="Удалить">
                          <i class="bi bi-trash"></i>
                        </a>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

  </div>



{% endblock %}

templates/app_accounts/user_edit.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
	{{ block.super }} - Редактирование профиля
{% endblock %}
{% block content %}

  <div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}
        <div class="hstack gap-3 my-4">
          <a class="btn btn-secondary nav-back" href="{% url 'app_accounts:user_detail' %}">Отмена</a>
          <button class="btn btn-success" type="submit">Сохранить</button>
        </div>
      {% endwith %}
    </form>
  </div>

{% endblock %}

templates/app_accounts/user_email_verify.html
{% extends 'shared/_base.html' %}
{% block title %}
	{{ block.super }} - Подтверждение адреса почты
{% endblock %}
{% block content %}
	<p class="mt-5">Мы отправили вам письмо со ссылкой, чтобы подтвердить адрес вашей почты.</p>
  <p>Проверьте вашу почту.</p>
  <div class="alert alert-secondary mt-2">
    <i class="bi bi-info-circle"></i>
    Если сообщение не пришло в течении получаса, проверьте папку "спам" или повторите попытку снова
  </div>
{% endblock %}

templates/app_accounts/user_email_verify_failed.html
{% extends 'shared/_base.html' %}
{% block title %}
	{{ block.super }} - Подтверждение адреса почты
{% endblock %}
{% block content %}
  <p class="mt-5">Не удалось подтвердить адрес почты!</p>
  <p>Ссылка не корректна или истек срок действия.</p>
{% endblock %}

templates/app_accounts/user_list.html
{% extends 'shared/_base.html' %}
{% block title %}
  {{ block.super }} - Список пользователей
{% endblock %}
{% block content %}
  <table class="table table-hover table-striped mt-5">
    <thead>
    <tr>
      <th>ФИО</th>
      <th>email</th>
      <th>Активен</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
      <tr>
        <td>{{ object.full_name }}</td>
        <td>{{ object.email }}</td>
        <td>
          {% if object.is_active %}
            <i class="bi bi-check text-success-emphasis "></i>
          {% else %}
            <i class="bi bi-x text-danger-emphasis "></i>
          {% endif %}
        </td>
        <td>
          <div class="btn-toolbar">
            <div class="btn-group btn-group-sm" role="group">
              {% if user.pk == object.pk %}
                <a href="{% url 'app_accounts:user_detail' %}" class="btn btn-outline-primary"><i
                    class="bi bi-pencil"></i></a>
              {% endif %}
              {% if perms.app_accounts.can_block_users and not user.pk == object.pk %}
                <a href="{% url 'app_accounts:user_block' object.pk %}" class="btn btn-outline-warning">
                  {% if object.is_active %}
                    <i class="bi bi-person"></i>
                  {% else %}
                    <i class="bi bi-person-lock"></i>
                  {% endif %}
                </a>
              {% endif %}
            </div>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/app_accounts/user_password_change.html
{% extends 'shared/_base.html' %}
{% load django_bootstrap5 %}
{% block title %}
	{{ block.super }} - Смена пароля
{% endblock %}
{% block content %}

  <div class="position-absolute top-50 start-50 translate-middle w-25">
    <form method="post">
      {% with WIDGET_ERROR_CLASS='is-invalid' %}
        {% csrf_token %}
        {% bootstrap_form form layout="floating" %}
        <div class="hstack gap-3 my-4">
          <a class="btn btn-secondary" href="{% url 'app_accounts:user_detail' %}">Отмена</a>
          <button class="btn btn-success" type="submit">Изменить пароль</button>
        </div>
      {% endwith %}
    </form>
  </div>

{% endblock %}